package com.wdd.bean;

public class Job {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_id
     *
     * @mbg.generated Sat Jun 23 19:25:44 CST 2018
     */
    private Integer jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_name
     *
     * @mbg.generated Sat Jun 23 19:25:44 CST 2018
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.user_id
     *
     * @mbg.generated Sat Jun 23 19:25:44 CST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_id
     *
     * @return the value of job.job_id
     *
     * @mbg.generated Sat Jun 23 19:25:44 CST 2018
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_id
     *
     * @param jobId the value for job.job_id
     *
     * @mbg.generated Sat Jun 23 19:25:44 CST 2018
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_name
     *
     * @return the value of job.job_name
     *
     * @mbg.generated Sat Jun 23 19:25:44 CST 2018
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_name
     *
     * @param jobName the value for job.job_name
     *
     * @mbg.generated Sat Jun 23 19:25:44 CST 2018
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.user_id
     *
     * @return the value of job.user_id
     *
     * @mbg.generated Sat Jun 23 19:25:44 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.user_id
     *
     * @param userId the value for job.user_id
     *
     * @mbg.generated Sat Jun 23 19:25:44 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}